l=int(input('podaj numer:'))
l=len(str(l))
match l:
    case 1:print("numer ma tylko jedną cyfre")
    case 2:print("numer ma dwie cyfry")
    case 3:print("numer ma trzy cyfry")
    case 4:print("numer ma cztery cyfry")
    case 5:print("numer ma pięć cyfr")
    case 6:print("numer ma sześć cyfr")
    case 7:print("numer ma siedem cyfr")
    case 8:print("numer ma osiem cyfr")
    case 9:print("numer ma dziewięć cyfr")
    case 10:print("numer ma dziesięć cyfr")
    case 11:print("numer ma jedynaście cyfr")
    case _:print('numer ma ',l," cyfr")
